### ISSUE TITLE
Would using "protected _SceneTree _" be better instead of "private _SceneTree _"?

### ISSUE THREAD

**Issue by magian1127** [Cat-Lips/GodotSharp.SourceGenerators#22]
```
[SceneTree(null, true)]
public partial class A: CharacterBody2D
```

```
public partial class B: A
```

When "B" needs to use a node, you must create another variable yourself.

**Comment by Cat-Lips** [comment]
Hi Magian.

Currently, both the _SceneTree class and the _ property need to be private so they don't conflict with any derived scene that also uses the SceneTree attribute (in which case the inherited scene is included anyway).  It could be done with a bit of name mangling, of course, but it might be better for the base class to provide protected access to the required parts of the tree (eg, `protected Label MyLabel => _.Layout.Label;`).  Alternatively, one could use unique names to get public properties.

**Comment by magian1127** [comment]
Okay, thank you.  I'll study it again.
