### ISSUE TITLE
When the child node "[Export] Node" is present, the parent node "[SceneTree]" becomes invalid and results in an error.

### ISSUE THREAD

**Issue by magian1127** [Cat-Lips/GodotSharp.SourceGenerators#23]
![image](https://user-images.githubusercontent.com/14800320/229772936-123b0f28-644b-48a8-ace7-360156abd27d.png)

```
public partial class AttackDetection : Area2D, IInteract
{
    [Export]
    private BaseCreature? Creature { get; set; }

    [Export]
    public Area2D? CreatureDefense { get; set; }
}
```
BaseCreature  error
```
[SceneTree(null, traverseInstancedScenes: true)]//[SceneTree] also reported an error
public partial class BaseCreature : CharacterBody2D
```

godot 4.0

**Comment by Cat-Lips** [comment]
Hi Magian.

To confirm, the issue occurs when the parent BaseCreature is assigned to AttackDetection.Creature?  Godot 4.0.1 wouldn't allow me to do that (because it would cause a cyclical node dependency).  Could you please upload a minimal project to reproduce the problem?

Cheers.

**Comment by magian1127** [comment]
[JZGLtest.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/11184649/JZGLtest.zip)
An error only occurs under specific conditions, but starting a new GODOT project does not produce the same error.

**Comment by Cat-Lips** [comment]
Nice work, Magian - definitely a bug.  Should have a fix ready soon :)

**Comment by Cat-Lips** [comment]
New pre-release version uploaded to Nuget.
 - 2.1.0-230411-1909.Release

**Comment by magian1127** [comment]
2.1.0-230411-1909.Release is working normally.
