### ISSUE TITLE
Implicit Conversions for Scene Tree Branches

### ISSUE THREAD

**Issue by waldnercharles** [Cat-Lips/GodotSharp.SourceGenerators#29]
I'd love to open a PR to add an implicit conversion for scene tree branches. I just don't like having to manually call `.Get()`. I was thinking of doing something like this:
```csharp
{{NSIndent}}{{indent}}            public static implicit operator {{node.Value.Type}}(__{{depth}}_{{node.Value.Name}} ___{{depth}}_{{node.Value.Name}}) => ___{{depth}}_{{node.Value.Name}}.Get();
```

Which would generate into something like:
```csharp
public static implicit operator Godot.Area2D(__0_Area ___0_Area) => ___0_Area.Get();
```

I tried to get this working locally but, I've been running into issues trying to confirm the functionality is working. For whatever reason the nuget package from this repo seems to work just fine, but pulling it into my csproj locally doesn't work. I'm likely doing something wrong.

I just added it to my csproj like so:
```xaml
<ProjectReference Include="..\GodotSharp.SourceGenerators\SourceGenerators\SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
```

**Comment by Cat-Lips** [comment]
Hey wc :)

Nice idea!  I wasn't too keen on .Get() either, but couldn't think of any other way to access a non-leaf node.  I initially toyed with the idea of a Node property, but that could have too easily conflicted with the naming of a node.  These days I just assign unique names to anything I want in script so I can access them directly (the package generates a property for anything marked with a unique name in the editor).

History aside, I think the implicit conversion will work well in most cases, so I'll do up a branch for your changes and some tests.

Cheers :)

**Comment by Cat-Lips** [comment]
PS:  I add the attached nuget config to my projects so I can make use of local package changes

[nuget.config.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/11796521/nuget.config.zip)

**Comment by Cat-Lips** [comment]
New pre-release package with requested changes uploaded to nuget.  Will formalise into 2.1 release in a few days to give early adopters time to provide feedback (just in case).
