### ISSUE TITLE
`HintAttribute.g.cs` is missing `using System;`

### ISSUE THREAD

**Issue by magian1127** [Cat-Lips/GodotSharp.SourceGenerators#36]
Error: CS0246.
Not everyone has used `global using`.

**Comment by Cat-Lips** [comment]
Thanks bud.  On it.

**Comment by Cat-Lips** [comment]
Here's the requested fix if you need something straight away.
Just getting a csc crash with my tests when I turn off explicit usings :/

[GodotSharp.SourceGenerators.2.2.1-231021-1714.Release.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/13059986/GodotSharp.SourceGenerators.2.2.1-231021-1714.Release.zip)
