### ISSUE TITLE
Compilation failure on export from OnImportEditorPlugin

### ISSUE THREAD

**Issue by dogboydog** [Cat-Lips/GodotSharp.SourceGenerators#40]
Version 2.3.0 (nuget) 

Error: 
```
\GodotSharp.SourceGenerators\GodotSharp.SourceGenerators.OnImportExtensions.OnImportSourceGenerator\OnImportEditorPlugin.g.cs:7
    CS0246 The type or namespace name 'EditorImportPlugin' could not be found (are you missing a using directive or an assembly reference?)goroutine 1 [running]:
```

I am not even using the [OnImport] attribute anywhere. I think you have to  put any references to editor-only classes inside an `#ifdef TOOLS`. It compiles in the editor but not when you export, where all the TOOLS code is compiled out. 
    
Thanks for the work on this package

**Comment by Cat-Lips** [comment]
Thanks DB.  Good find.

I have uploaded a new pre-release package.  Let me know if that is all working for you and I will close and release 2.3.1.

Cheers :)

**Comment by dogboydog** [comment]
2.3.1-231211-0953.Release fixed export for me. Thank you!
