### ISSUE TITLE
Exclude CodeAnalysis DLLs from exports? 

### ISSUE THREAD

**Issue by dogboydog** [Cat-Lips/GodotSharp.SourceGenerators#42]
This might just be a documentation question, but is there a way to exclude `Microsoft.CodeAnalysis.dll` and `Microsoft.CodeAnalysis.CSharp.dll` from the `data_` folder when exporting the game? 

I tried to do some research and experimented with adding ` PrivateAssets="All"` to my PackageReference but it didn't seem to make a difference.  Just wondering since I was able to manually delete these two files without seeming to impact the game at runtime, and they are almost 9 MB together - there may be other DLLs pulled in this way for code analysis as well that I wouldn't think would be needed at runtime. 

### Project setup 

source_gen/SourceGen.csproj
```
    <ItemGroup>
        <PackageReference Include="GodotSharp.SourceGenerators" Version="2.3.1" ExcludeAssets="runtime"/>
    </ItemGroup>
 ```
Main.csproj 
```
    <ItemGroup>
        <ProjectReference Include="source_gen\SourceGen.csproj" OutputItemType="analyzer"/>
    </ItemGroup>
```

**Comment by Cat-Lips** [comment]
Hi DG.  Good find.

I've added `PrivateAssets="all"` to the package and the dlls are no longer copied.
(You'll just need to clear out your bin from any previous builds.)

Please test with the following package, just to make sure everything runs ok:
[GodotSharp.SourceGenerators.2.3.2-240105-2340.Release.nupkg.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/13842161/GodotSharp.SourceGenerators.2.3.2-240105-2340.Release.nupkg.zip)

**Comment by dogboydog** [comment]
Gave it a try. I haven't actually installed a nuget package from a local file before. 

I did this: 
dotnet add package GodotSharp.SourceGenerators -s E:/LocalNugetFeed --prerelease
dotnet clean

Then after re-exporting, it does seem the CodeAnalysis DLLs are gone. Thank you
