### ISSUE TITLE
Generation fails if the scene has a node with a built-in script

### ISSUE THREAD

**Issue by jwright159** [Cat-Lips/GodotSharp.SourceGenerators#43]
```
The given key '' was not present in the dictionary.
```

External scripts are defined in the tscn with `script = ExtResource("some_id")`. Built-in scripts are defined with `script = SubResource("some_id")`. The scraper only checks for `ExtResource`, so `SubResource` fails the regex, and and the id is set to `""`. This isn't present in the resources dictionary.

I would recommend just ignoring build-in scripts, since by definition it doesn't have a C# class.

**Comment by Cat-Lips** [comment]
Thanks Jady.  Good find.  I'll create some tests and add your fix :)
