### ISSUE TITLE
All custom classes will be black.

### ISSUE THREAD

**Issue by magian1127** [Cat-Lips/GodotSharp.SourceGenerators#5]
![image](https://user-images.githubusercontent.com/14800320/133433471-4c8ab81e-bf50-4b68-924a-54507a280d2d.png)
vs 2019 16.XX.X

The part of the arrow will turn black.
All custom classes will be black.
For this reason, I had to stop using it.

箭头的部分会变成黑色.
所有自定义的类都会是黑色.
就应为这个原因,我只好不使用了.

**Comment by Cat-Lips** [comment]
Hi Magian, thanks for letting me know.  I was unable to replicate with my own inferred example.  If you would like me to investigate further, could you please post a minimal Godot project?  Thanks.

**Comment by magian1127** [comment]
[Source.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/7191106/Source.zip)
![image](https://user-images.githubusercontent.com/14800320/133918404-2ea26f83-0643-423e-945f-4f8f37451055.png)

vs 2019 16.11.3
After opening vs, wait until all modules of vs are loaded, and this will appear.
打开VS后,要等待VS所有模块加载完毕后,就会出现这个问题.

**Comment by Cat-Lips** [comment]
Hi Magian, thanks for that.  I was able to replicate and will investigate.

Cheers :)

**Comment by Cat-Lips** [comment]
This is a known issue in Visual Studio 2019. 
The issue is not present in Visual Studio 2022.
