### ISSUE TITLE
Regression: incorrect scene path being generated with `res:/` instead of `res://`

### ISSUE THREAD

**Issue by ttencate** [Cat-Lips/GodotSharp.SourceGenerators#53]
Using `OnInstantiate` in 2.1.1, I got this code:

```csharp
using System;
using System.ComponentModel;

using Godot;

partial class LoadingScreen
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    private static PackedScene __scene__;

    [EditorBrowsable(EditorBrowsableState.Never)]
    private static PackedScene __Scene__ => __scene__ ??= GD.Load<PackedScene>("res://ui/LoadingScreen.tscn");

    public static LoadingScreen Instantiate()
    {
#if NET6_0 || NET7_0  // Godot 4.0
        var scene = __Scene__.Instantiate<LoadingScreen>();
#else
        var scene = __Scene__.Instance<LoadingScreen>();
#endif
        scene.Init();
        return scene;
    }

    protected LoadingScreen() {}
}
```

~~In~~ Since 2.2.1, it looks like this instead:

```csharp
using System;
using System.ComponentModel;

using Godot;

partial class LoadingScreen
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    private static PackedScene __scene__;

    [EditorBrowsable(EditorBrowsableState.Never)]
    private static PackedScene __Scene__ => __scene__ ??= GD.Load<PackedScene>("res:/ui/LoadingScreen.tscn");

    public static LoadingScreen Instantiate()
    {
#if NET6_0 || NET7_0  // Godot 4.0
        var scene = __Scene__.Instantiate<LoadingScreen>();
#else
        var scene = __Scene__.Instance<LoadingScreen>();
#endif
        scene.Init();
        return scene;
    }

    protected LoadingScreen() {}
}
```

(I'm not sure about 2.2.0 because my code doesn't seem to build with it.)

The difference is only one character, but an important one: `res:/ui/LoadingScreen.tscn` does not load, resulting in a `NullReferenceException`. I think `res://` should always have two slashes; https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html does not mention any exceptions.

Edit: the input code is very simple so I'll post it here rather than simplifying it further:

```csharp
using Godot;
using System;

public partial class LoadingScreen : Control {
	private Label? _description;

	[OnInstantiate]
	public void Init() {
	}

	public override void _Ready() {
		_description = GetNode<Label>("%Description");
	}

	public void SetDescription(string description) {
		if (_description != null) {
			_description.Text = description;
		}
	}
}
```

**Comment by Cat-Lips** [comment]
Hey TT,

What version of Godot are you using?

**Comment by Cat-Lips** [comment]
I've identified where the error would occur but haven't been able to replicate as yet.

Does it also occur in the latest release (of this and Godot)?

**Comment by ttencate** [comment]
`4.2.1.stable.mono.official.b09f793f5`

It occurred in GodotSharp.SourceGenerators 2.3.2 as well. That's how I found out about it.

**Comment by Cat-Lips** [comment]
Thanks bud.  Looking into it now.

**Comment by Cat-Lips** [comment]
Can you run this and let me know how it goes?
I ran with Godot 4.2.1 stable, .NET8.0 and Generators 2.3.2.

[MyTest.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/14829586/MyTest.zip)

**Comment by ttencate** [comment]
I can't reproduce it anymore. Neither with your project, nor with my own. It was quite consistently reproducible before, even when switching back and forth between versions. Mysterious! Sorry for the noise; I'll do some more digging if it ever comes back.

**Comment by Cat-Lips** [comment]
Yes, very strange, but definitely thanks for reporting.  Better to be aware in case it resurfaces :)
