### ISSUE TITLE
public SceneTree gen code?

### ISSUE THREAD

**Issue by jasonswearingen** [Cat-Lips/GodotSharp.SourceGenerators#62]
Hi, I'd like to ask if there is any technical reason for SceneTree generated classes that prevent it from being public?   If not, would you consider accepting a PR where I make public optional, such as `[SceneTree(isPublic=true)]`?

Thank you

**Comment by jasonswearingen** [comment]
it looks rather complex to add a conditional `isPublic` toggle, so I think this (untested) simple workaround to the `SceneTreeTemplate.sbncs` will work:

![image](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/assets/814134/e3cf419e-4df7-477e-bdc2-2b3f408c7f50)

that way it's `protected internal` by default, and If someone want's to make `_SceneTree` truely public, they can add a new Property exposing it.

**Comment by Cat-Lips** [comment]
Hi Jason.

Currently, the SceneTree property and class are private to prevent naming conflicts when one inherits, but with a few small changes, I think we could work around this to add customisable scope.

However, since uniquely named nodes are exposed as public properties, it could encourage better design to keep the SceneTree property and class private so a scene can provide more targeted access to relevant nodes.

What do you think?

**Comment by jasonswearingen** [comment]
ahh, you are probably right about naming conflicts.  I am just starting out, so I'll try using the above hack and see if I end up okay or have to change it again.  

I think making the `_SceneTree` class public might be okay, and let the user decide if they want to expose the instance variable....   but okay to take it slow.

FYI I am trying to use this hack for exposing some "native" .tscn files to csharp (like an imported "scene" from blender).   If you have a better idea on how to accomplish that I'd love to hear.

**Comment by Cat-Lips** [comment]
Ah, sounds like you might need a post import script.  You can inherit from EditorScenePostImport and override _PostImport.  Whatever you return from this will be used by Godot as the imported scene.  (Scroll down in the import options to see where to assign the script.)

**Comment by jasonswearingen** [comment]
Thank you so much for this hint.  For anyone else reading this, I found this post which explains @Cat-Lips suggestion in detail: https://gamedev.stackexchange.com/questions/208180/godot-importing-mesh-files-without-the-inheritances-of-useless-spatial-nodes

I'll give this a try also.   Feel free to close this if you don't think anything is actionable right now.

**Comment by Cat-Lips** [comment]
Ok, glad you're on the right track.  I'll close for now, but happy to add custom scope if needed and the uniquely named node feature is insufficient.  Cheers :)
