### ISSUE TITLE
No #nullable annotation generated when using nullable references

### ISSUE THREAD

**Issue by xill47** [Cat-Lips/GodotSharp.SourceGenerators#63]
This code

```csharp
[OnInstantiate("private")]
private void Init(CardStateNode? initialState)
{
    StartingState = initialState;
}
```

Produces this error

Error CS8669 : The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.

As far as I know, all that is required is `#nullable restore` annotation at the start of the file, I can probably experiment with that later myself

**Comment by Cat-Lips** [comment]
Thanks xill.  I think you're right.  I'll do a fix and confirm :)

**Comment by Cat-Lips** [comment]
Ok.  [OnInstantiate] can now support nullability using the attached nuget (zipped).  Feel free to review/test for your use case.

The only other attribute that could have an outwardly facing annotated type is [Notify].  Haven't done that yet, but will do so soon.

[GodotSharp.SourceGenerators.2.4.0-240624-1825.Release.nupkg.zip](https://github.com/user-attachments/files/15952564/GodotSharp.SourceGenerators.2.4.0-240624-1825.Release.nupkg.zip)

**Comment by Cat-Lips** [comment]
Done for [Notify].  Added an Init<PropertyName> method to assign a default value.  If all good, we can merge.

[GodotSharp.SourceGenerators.2.4.0-240625-1312.Release.nupkg.zip](https://github.com/user-attachments/files/15964565/GodotSharp.SourceGenerators.2.4.0-240625-1312.Release.nupkg.zip)

**Comment by xill47** [comment]
Thanks for such quick fix! I'll try to check it out todays evening

**Comment by xill47** [comment]
This version fixed everything for me, thanks
