### ISSUE TITLE
Cannot resolve symbol 'LayerNames'

### ISSUE THREAD

**Issue by SmialyKot** [Cat-Lips/GodotSharp.SourceGenerators#65]
## Issue
Hey, I've encountered an issue when trying to use `LayerNames`, other attributes work as expected.

As a test I've applied all attributes and only 'LayerNames' can't be resolved:
![layer_names](https://github.com/user-attachments/assets/b5fae706-e4eb-411d-af03-9b16114a7461)

I've tried re-importing the nuget package to no avail.

Compile error:
```
Error CS0246 : The type or namespace name 'LayerNamesAttribute' could not be found (are you missing a using directive or an assembly reference?)
Error CS0246 : The type or namespace name 'LayerNames' could not be found (are you missing a using directive or an assembly reference?)
```
## My setup:
Godot 4.2.2
godotsharp.sourcegenerators 2.3.4
JetBrains Rider 2024.1.4

Layers section in my `project.godot`:
```
[layer_names]

3d_render/layer_20="Decal layer"
3d_physics/layer_2="Camera Probe Layer"
3d_physics/layer_3="Camera Occlusion"
```

**Comment by Cat-Lips** [comment]
Apologies for the confusion.  LayerNames is still in pre-release.  I'll do a 2.4.0 release when I get back from holiday.  (I'll make sure to tag pre-release features in description in future :D)

**Comment by SmialyKot** [comment]
Thanks
