### ISSUE TITLE
[OnInstantiate] does not search all project scene files

### ISSUE THREAD

**Issue by valkyrienyanko** [Cat-Lips/GodotSharp.SourceGenerators#67]
### My project is setup so scripts are separate from scene files
I have always organized my project by having a `res://Scenes` folder for all `.tscn` files and a `res://Scripts` folder for all `.cs` files. I'm not sure how I feel about keeping the `.tscn` files next to the `.cs` files. I might just refactor my entire projects file structure just to use this attribute.

### The Issue
I get the following error when I try to use `[OnInstantiate]` in `UIOptions.cs`. This is because there is no `UIOptions.tscn` file in this path as its located under `res://Scenes` not `res://Scripts`.
```
Error: Cannot open file 'res://Template/Scripts/UI/Options/UIOptions.tscn'.
```

Actual Scene Path: `res://Scenes/Prefabs/UI/options.tscn`
Actual Script Path: `res://Template/Scripts/UI/Options/UIOptions.cs`

**Comment by valkyrienyanko** [comment]
I've decided I'm just going to refactor my entire project to make it so all scripts are right next to their respective scene files.

**Comment by Cat-Lips** [comment]
Yes, true.  I have an alternate path for tscn parsing on SceneTree, but not for any other attribute.  It would suck having to specify an alternative for all these attribute-based generators, so unfortunately this paradigm does tend to lend itself to grouping scene files with source code.

If it helps, I nest my tscn/tres files under my cs files in Visual Studio:  https://github.com/Cat-Lips/F00F (see .filenesting.json)

**Comment by valkyrienyanko** [comment]
You could tell users to include the following in their main Godot `.csproj` file.

```xml
<ItemGroup>
    <AdditionalFiles Include="**\*.tscn" />
</ItemGroup>
```

And then you could loop through each `.tscn` file in your source generator and parse it.

**Comment by Cat-Lips** [comment]
Anyway, I'll see what I can do to fix this for you.

**Comment by Cat-Lips** [comment]
> But in your case, I've just realised that the names are different (options.tscn/UIOptions.cs), so even if they were in the same folder or using an additional files lookup, we'd probably still need to use an attribute property...

Or... could parse tscn files to get cs path and create a static lookup

**Comment by Cat-Lips** [comment]
Hi Valk.  You happy for me to close this issue?

**Comment by valkyrienyanko** [comment]
I've gotten use to putting my scripts next to scene files.

**Comment by Cat-Lips** [comment]
Thanks bud
