### ISSUE TITLE
[OnInstantiate] Unable to instantiate because of wrong resource path

### ISSUE THREAD

**Issue by Galabar64** [Cat-Lips/GodotSharp.SourceGenerators#74]
When I use [OnInstantiate], the code generated has an error in the resource path. It ends up with just 1 **/** after the **res:**

```csharp
private static PackedScene __Scene__ => __scene__ ??= GD.Load<PackedScene>("res:/customers/Customer.tscn");
```

Because of that, Godot is unable to find the file:

```
ERROR: Cannot open file 'res:/customers/Customer.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1367)
ERROR: Failed loading resource: res:/customers/Customer.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:283)
ERROR: Error loading resource: 'res:/customers/Customer.tscn'.
   at: load (core/core_bind.cpp:74)
```

For the reproduction, I followed the example in the README.

Godot 4.3.0
net8.0
Linux

**Comment by Cat-Lips** [comment]
Thanks GB.  Away this week, but will address next week.  Cheers :)

**Comment by Cat-Lips** [comment]
Here's the fix.  Could you pls test for your use case and if all good I'll merge to main.  Cheers :)

[GodotSharp.SourceGenerators.2.4.1-241015-1409.Release.zip](https://github.com/user-attachments/files/17372100/GodotSharp.SourceGenerators.2.4.1-241015-1409.Release.zip)

**Comment by Galabar64** [comment]
It worked! Thanks a lot and have a nice day ^^

**Comment by Cat-Lips** [comment]
Uploaded new pre-release nuget package with this fix (241016)
