### ISSUE TITLE
[SceneTree] generated weird type `_SceneTree.__0_Area3D`

### ISSUE THREAD

**Issue by valkyrienyanko** [Cat-Lips/GodotSharp.SourceGenerators#75]
## Steps to Reproduce
1. Clone https://github.com/ValksGodotTools/Template
2. Switch to spaceship-3d branch
3. Make sure you are using **Redot** v4.4.dev.mono.gh [1c7d7fa8d] (their latest beta release at the time of writing this)
4. Delete the CSharpFolder from Redots release folder and replace it with the CSharpFolder from the latest Godot 4.4 release folder (needed because CSharpFolder not built properly on Redot for some reason)

5. Make sure you are on this commit in case I change the code the future

![Untitled](https://github.com/user-attachments/assets/88276192-b2b6-4202-b944-98e1324bcf46)
Commit SHA: `7723cdc2949d4373bbce971cc68b6ca18a6bbd84`

6. Open up the SpaceShip.cs script located in `res://Genres/3D FPS/Scenes/SpaceShip.cs`
7. Notice the weird type name

## Remarks
Have not tested on Godot, don't know if this is a Redot specific bug.

I recently switched from VS2022 to VSCode if that matters.

## Screenshots
![Untitled](https://github.com/user-attachments/assets/77aa2385-0a31-4274-b4f4-f8224a005380)

![Untitled](https://github.com/user-attachments/assets/89334e56-3f07-42ec-907c-04d05e9f0f62)

![Untitled](https://github.com/user-attachments/assets/b5b8471f-9fb0-4792-906b-94d1f7f9aab0)

**Comment by Cat-Lips** [comment]
Hi Valk.

All those weirdly named types in _SceneTree are wrappers around the actual Godot type to implement the scene tree navigation (not required by leaf nodes).  They do have implicit operators that allow them to passed around and used or cast to the Godot type or can be retrieved using a Get() method, eg:

```
var t = _.Area3D.Get();
var t = (Area3D)_.Area3D;
var t = _.Area3D as Area3D;
var t = Area3D; // where you define property: private Area3D Area3D => _.Area3D;
var t = Area3D; // where generator defines property from unique_name_in_owner = true
```

**Comment by valkyrienyanko** [comment]
I just realized I can also do `Area3D t = _.Area3D;` 👀
