### ISSUE TITLE
[SceneTree] Missing a typesafe way to access the scenes root node

### ISSUE THREAD

**Issue by benjiwolff** [Cat-Lips/GodotSharp.SourceGenerators#81]
I use [SceneTree("prefab.tscn")] to access the tree from a descendant node and would like to access the root in the same way. Unfortunately, the root seems to be absent in the generated _-property.

**Comment by benjiwolff** [comment]
Ah, the issue is more broad I see. Using SceneTree on a descendant node causes the paths to be evaluated against that node, which will obviously cause NullReferenceExceptions at runtime. I expected this to be the intended way to use [SceneTree] since the generated _-property is private. I guess I will wrap it to make it publicly accessible.

**Comment by Cat-Lips** [comment]
Yeah, [SceneTree] was only designed to replicate from root, so unfortunately, doesn't really work for scripts on child nodes or provide type-safe access to the root object.  As noted above, there's been some discussion on how to add this (thanks for your contribution there, btw).

With current functionality, I would be inclined to create a separate scene for anything complex enough to require a script (especially if re-use is required), or, if simple, access & initialise from root.  If you still need a sub-node-script, you could have an Init method to receive the root (called on _ready) or use GetNode directly.  (You could also use the uniquely named node within scene feature to generate publicly accessible properties on the root.)

**Comment by Cat-Lips** [comment]
Closing this.  Will add to #69.
