### ISSUE TITLE
SceneTree doesn't find instanced scene with filename over certain number of characters??

### ISSUE THREAD

**Issue by TraverserEternal** [Cat-Lips/GodotSharp.SourceGenerators#90]
I'm experiencing a really strange behavior with instanced scenes. I have a few scripts in folders like so: 
![image](https://github.com/user-attachments/assets/9f8cdba3-d1e7-43c1-ad0d-1184d46edcaa)
The important part here is that there is a folder, with a .cs file and a .tscn file, both of which share a name. The classname within the .cs file is also matches the filenames.

With certain lengthy names, the [SceneTree] Attribute doesn't pick up nodes that are of that class/scene (I tried to determine which of these were the case, but I kept getting generation errors when I had mismatched scriptname/scenename files). However, this length appears to be dependent on the letters being typed. For example, TestCaseWithM is not found, while TestCaseWith is, and TestCaseWithaa is also found. 

I can't really tell, but my best guess is there's a problem with the scraper?

Thanks in advance for any help. This tool is really fantastic!

**Comment by TraverserEternal** [comment]
Just to be clear: 
  The name of the *Node*(i.e. the name that you give the instanced scene in the tree) doesn't seem to have an effect
  
  Successful Names:
  - Propensit
  - Propensity
  - PropensitiesDisp
  - TestCaseWithaa
  - TestCaseWith
  
  Failed Names:
  - PropensityDisplay
  - PropensitiesDispl
  - PropensitiesDisplay
  - TestCaseWithMoreCharacters
  - TestCaseWithM

**Comment by Cat-Lips** [comment]
Hi TE.

Thank you for your investigation, however I wasn't able to replicate the issue at my end.  Was there an error compiling or is it a runtime issue?

(There is (still!) a 260 char path limit on Windows, so could have something to do with that.  By default, the source generator avoids emitting compiler generated files and truncates filenames to 255, but could be something else related.)

**Comment by TraverserEternal** [comment]
Strange. I will occasionally get this compilation error when I've renamed something 
![image](https://github.com/user-attachments/assets/f1345fb3-5cd9-47d8-99e1-61a63575c718)
And I once saw a similar source generator error like it. I'll try to reproduce that one as well

**Comment by TraverserEternal** [comment]
![image](https://github.com/user-attachments/assets/78f343df-298b-4227-8900-d4d5fb69c2e3)
This one, I get when I add an instanced scene that works, and then rename the file to something that doesn't

**Comment by TraverserEternal** [comment]
But the error is not that the source generation fails, but rather that intellisense doesn't pick up the instanced scene in vscode, and any attempt to compile it with a reference tells me that the source generation has skipped over it, that it simply isn't a reference in my class

**Comment by TraverserEternal** [comment]
Ah! it looks like my vscode is the problem. The source generator is working fine, but in the intellisense it doesn't actually pick up  the scene in the autocomplete. Which is strange, but not a problem with this repo. Sorry for the trouble!

**Comment by TraverserEternal** [comment]
Alright, my problem was that I needed the latest SDK. Hope this helps anyone with the same problem, and thank you @Cat-Lips for your help

**Comment by Cat-Lips** [comment]
Thanks mate.  Glad you got it sorted :)

Good luck with your game! :D
