### ISSUE TITLE
Compilation.GetFullName assumes running on Windows

### ISSUE THREAD

**Issue by federicoasara** [Cat-Lips/GodotSharp.SourceGenerators#91]
Hello there!
In my Godot C# project, I have the following (simplified) structure:

```
.../Alpha/MyObject.cs 
.../Beta/MyObject.cs  
```

When a TSCN file refers to `Alpha.MyObject`, then [this logic](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/blob/609ebd066d83a5d61607d084913a72875d715c67/SourceGenerators/Utilities/Extensions/CompilationExtensions.cs#L20C49-L21C67) comes into play.

It looks like this code is assuming we are always running on Windows, given that replaces "/" with "\" in resource paths. We should probably use `System.IO.Path.DirectorySeparatorChar` instead.

Unfortunately I am not able to set up a PR right now, since a clean test build on Linux gives the following errors and I cannot verify that my fix won't break anything else:

```
  Godot 4 Tests failed with 4 error(s) (1.6s)
    /home/fed/gh/GodotSharp.SourceGenerators/Godot 4 Tests/.godot/mono/temp/obj/Debug/GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/GodotTests.TestScenes.SceneWithSameName.g.cs(42,21): error CS1520: Method must have a return type
    /home/fed/gh/GodotSharp.SourceGenerators/Godot 4 Tests/.godot/mono/temp/obj/Debug/GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/GodotTests.TestScenes.SceneWithSameName.g.cs(59,36): error CS0246: The type or namespace name 'root' could not be found (are you missing a using directive or an assembly reference?)
    /home/fed/gh/GodotSharp.SourceGenerators/Godot 4 Tests/.godot/mono/temp/obj/Debug/GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/GodotTests.TestScenes.Script.SceneWithSameName.g.cs(42,21): error CS1520: Method must have a return type
    /home/fed/gh/GodotSharp.SourceGenerators/Godot 4 Tests/.godot/mono/temp/obj/Debug/GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/GodotTests.TestScenes.Script.SceneWithSameName.g.cs(59,36): error CS0246: The type or namespace name 'root' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by Cat-Lips** [comment]
Thanks for that.  I'll have to setup a Linux environment for future testing.

For now, I've made the change.  Can you test on your side?

[GodotSharp.SourceGenerators.2.5.1-241217-1202.Release.nupkg.zip](https://github.com/user-attachments/files/18159026/GodotSharp.SourceGenerators.2.5.1-241217-1202.Release.nupkg.zip)

**Comment by Cat-Lips** [comment]
Ok, great.  I'll do a new pre-release nuget.  Cheers.
